var TIER={S:0,A:1,B:2,C:3,D:4,E:5};
var RNAMES={common:"普通",uncommon:"稀有",rare:"超稀有",legendary:"传奇",secret:"神秘"};
var RCOLORS={common:{border:"#6b7280",bg:"linear-gradient(145deg,#374151,#1f2937)"},uncommon:{border:"#3b82f6",bg:"linear-gradient(145deg,#1e40af,#1e3a8a)"},rare:{border:"#a855f7",bg:"linear-gradient(145deg,#7c3aed,#6d28d9)"},legendary:{border:"#f59e0b",bg:"linear-gradient(145deg,#d97706,#b45309)"},secret:{border:"#9b59b6",bg:"linear-gradient(145deg,#8e44ad,#6c3483)"}};
var TCOLORS={S:"#ef4444",A:"#f97316",B:"#eab308",C:"#22c55e",D:"#64748b"};
function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");}
function getIcon(j){var e=j.effect||"";if(e.indexOf("X")>=0)return"✖";if(e.indexOf("Mult")>=0||e.indexOf("mult")>=0)return"◆";if(e.indexOf("Chips")>=0)return"◇";if(e.indexOf("$")>=0)return"●";return"★";}
function getIconColor(j){var e=j.effect||"";if(e.indexOf("X")>=0)return"#f59e0b";if(e.indexOf("Mult")>=0)return"#e94560";if(e.indexOf("Chips")>=0)return"#22c55e";if(e.indexOf("$")>=0)return"#fcd34d";return"#94a3b8";}
function svg(j,sz){var r=j.rarity||"common";var c=RCOLORS[r]||RCOLORS.common;var t=j.tier||"C";var tc=TCOLORS[t]||"#64748b";var icon=getIcon(j);var ic=getIconColor(j);var nm=j.name_cn||j.name||"";var en=j.name||"";var ltr=nm.charAt(0)||"?";var w=140,h=200,rx=12;var id=j.id.replace(/[^a-zA-Z0-9]/g,"");var s=["<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 "+w+" "+h+"" style="width:"+sz+"px;height:"+(sz*1.43)+"px">"];s.push("<defs><linearGradient id="g"+id+"" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color=""+c.border+"" stop-opacity="0.15"/><stop offset="100%" stop-color=""+c.border+"" stop-opacity="0.03"/></linearGradient></defs>");s.push("<rect x="2" y="2" width=""+(w-4)+"" height=""+(h-4)+"" rx=""+rx+"" fill=""+c.bg+"" stroke=""+c.border+"" stroke-width="2"/>");s.push("<rect x="6" y="6" width=""+(w-12)+"" height=""+(h-12)+"" rx=""+(rx-2)+"" fill="url(#g"+id+")"/>");s.push("<rect x="6" y="6" width=""+(w-12)+"" height="5" rx=""+(rx-2)+"" fill=""+c.border+"" opacity="0.5"/>");s.push("<circle cx=""+(w/2)+"" cy="52" r="26" fill=""+c.border+"" opacity="0.85"/>");s.push("<circle cx=""+(w/2)+"" cy="52" r="22" fill="none" stroke="rgba(255,255,255,0.12)" stroke-width="1.5"/>");s.push("<text x=""+(w/2)+"" y="60" text-anchor="middle" font-size="22" font-weight="bold" fill="white" font-family="sans-serif">"+esc(ltr)+"</text>");s.push("<text x=""+(w/2)+"" y="88" text-anchor="middle" font-size="9.5" font-weight="bold" fill="white" font-family="sans-serif">"+esc(nm.substring(0,6))+"</text>");s.push("<text x=""+(w/2)+"" y="100" text-anchor="middle" font-size="7" fill="rgba(255,255,255,0.45)" font-family="sans-serif">"+esc(en.substring(0,10))+"</text>");s.push("<text x=""+(w/2)+"" y="122" text-anchor="middle" font-size="20" fill=""+ic+"" font-family="sans-serif">"+icon+"</text>");s.push("<foreignObject x="10" y="128" width=""+(w-20)+"" height="52"><div xmlns="http://www.w3.org/1999/xhtml" style="font-size:7px;color:rgba(255,255,255,0.6);font-family:sans-serif;text-align:center;overflow:hidden;line-height:1.35;">"+esc((j.effect||"").substring(0,55))+"</div></foreignObject>");s.push("<rect x="6" y=""+(h-24)+"" width=""+(w-12)+"" height="18" rx=""+(rx-2)+"" fill=""+tc+"" opacity="0.9"/>");s.push("<text x=""+(w/2)+"" y=""+(h-11)+"" text-anchor="middle" font-size="9" font-weight="bold" fill="white" font-family="sans-serif">T"+esc(t)+" · "+RNAMES[r]+"</text>");s.push("</svg>");return s.join("");}
function cardHTML(j){var r=j.rarity||"common";var t=j.tier||"";var tg="";if(j.tags&&j.tags.length){tg=j.tags.slice(0,4).map(function(x){return"<span class="tag">"+esc(x)+"</span>";}).join("");}var tH=t?"<span class="tier t-"+t.toLowerCase()+"">"+t+"</span>":"";var s=svg(j,130);return"<div class="card "+r+"" onclick="show('"+j.id+"')" data-id=""+j.id+""><div class="card-img">"+s+"</div><div class="cn"><b>"+esc(j.name_cn||j.name||"")+"</b><br><span class="en">"+esc(j.name||"")+"</span></div><div class="cr"><span class="ct "+r+"">"+RNAMES[r]+"</span>"+tH+"</div><p class="ce">"+esc((j.effect||"").substring(0,50))+"</p><div class="tags">"+tg+"</div></div>";}
function show(id){var j=CARD_DATA.find(function(x){return x.id===id;});if(!j)return;var syn=j.synergy||[];var sH=syn.length?"<div class="ms"><h4>推荐协同</h4><ul>"+syn.map(function(s){return"<li>"+esc(s)+"</li>";}).join("")+"</ul></div>":"";var tH=j.tier?"<span class="tier t-"+j.tier.toLowerCase()+"">"+j.tier+"</span>":"";var cH=j.combo_tips?"<div class="mc-tip"><h4>组合思路</h4><p>"+esc(j.combo_tips)+"</p></div>":"";var s=svg(j,180);document.getElementById("modal-body").innerHTML="<div style="display:flex;justify-content:center;margin-bottom:20px">"+s+"</div><h2 class="mn">"+esc(j.name_cn||j.name||"")+"</h2><div class="msub">"+esc(j.name||"")+"</div><div class="mm"><span class="ct "+j.rarity+"">"+RNAMES[j.rarity]+"</span>"+tH+"<span class="stat-pill"><strong>费用:</strong>"+j.cost+"</span></div><p class="me">"+esc(j.effect||"")+"</p>"+sH+cH;document.getElementById("modal").classList.add("on");}
function closeModal(){document.getElementById("modal").classList.remove("on");}
function switchTab(name){document.querySelectorAll(".tab").forEach(function(t){t.classList.remove("on");});document.querySelectorAll(".nav").forEach(function(n){n.classList.remove("active");});document.getElementById("tab-"+name).classList.add("on");document.getElementById("tab-"+name+"-btn").classList.add("active");}
function doSearch(q){var lq=q.toLowerCase().trim();if(!lq){document.getElementById("search-grid").innerHTML="<div class="empty">输入关键词搜索...</div>";return;}var r=CARD_DATA.filter(function(j){return(j.name_cn||"").toLowerCase().indexOf(lq)>=0||(j.name||"").toLowerCase().indexOf(lq)>=0||(j.effect||"").toLowerCase().indexOf(lq)>=0||(j.tags||[]).some(function(t){return t.toLowerCase().indexOf(lq)>=0;})||(j.synergy||[]).some(function(s){return s.toLowerCase().indexOf(lq)>=0;});});r.sort(function(a,b){return(TIER[a.tier]||9)-(TIER[b.tier]||9);});if(r.length){document.getElementById("search-grid").innerHTML="<div class="stat-bar"><span class="stat-pill">找到 <strong>"+r.length+"</strong> 张卡牌</span></div>"+r.map(cardHTML).join("");}else{document.getElementById("search-grid").innerHTML="<div class="empty">没有找到「"+esc(q)+"</div>";}}
document.addEventListener("DOMContentLoaded",function(){var s=CARD_DATA.slice().sort(function(a,b){return(TIER[a.tier]||9)-(TIER[b.tier]||9);});document.getElementById("joker-grid").innerHTML=s.map(cardHTML).join("");document.getElementById("search-grid").innerHTML="<div class="empty">输入关键词搜索卡牌...</div>";});
document.getElementById("modal").onclick=function(e){if(e.target===this)closeModal();};
